[#ftl]
[@b.head/]
[@b.grid items=students var="student" sortable="true" id="alterationStudentGrid"]
  [@b.row]
    [@b.boxcol/]
    [@b.col property="code" title="学号" width="10%" classname="stdCode"/]
    [@b.col property="name" title="姓名" width="8%" classname="stdName"]
      [@b.a href="search!info?id="+student.id target="_blank" title="查看学籍信息"]${student.name}[/@]
    [/@]
    [@b.col property="person.gender.name" title="性别" width="5%"/]
    [@b.col property="state.grade.code" title="年级" width="5%" classname="stdGrade"/]
    [@b.col property="state.department.name" title="院系" width="10%" classname="departName"]
       [#if student.state.department.shortName??]${student.state.department.shortName}[#else]${student.state.department.name}[/#if]
    [/@]
    [@b.col property="state.major.name" title="专业" classname="majorName"]
      ${(student.state.major.name)!} ${(student.state.direction.name)!}
    [/@]
    [@b.col property="stdType.name" title="学生类别" width="8%" classname="stdTypeName"/]
    [@b.col property="beginOn" title="入学年月" width="8%"]${(student.beginOn?string("yyyy-MM"))!}[/@]
    [@b.col property="state.squad.name" sort="student.state.squad" title="班级"/]
  [/@]
[/@]
[@b.foot/]
