[#ftl]
[@b.head/]
[@b.grid items=admissions var="admission"]
  [@b.row]
    [@b.boxcol /]
      [@b.col title="std.state.grade" property="std.state.grade" width="5%"][/@]
      [@b.col title="attr.stdNo" property="std.code" width="10%"][/@]
      [@b.col title="attr.personName" property="std.name" width="10%"][/@]
      [@b.col title="录取年月" property="enrollOn" width="11%"]${((admission.enrollOn)?string("yyyy-MM-dd"))?default("")}[/@]
      [@b.col title="录取院系" property="department.name" width="12%"][/@]
      [@b.col title="录取专业/方向" property="major.name" width="12%"][/@]
      [@b.col title="通知书号" property="letterNo" width="10%"][/@]
      [@b.col title="第几志愿" property="admissionIndex" width="5%"][/@]
      [@b.col title="入学方式" property="enrollMode.name" width="10%"][/@]
      [@b.col title="培养方式" property="educationMode.name" width="10%"][/@]
  [/@]
[/@]
[@b.foot/]
