[#ftl]
[@b.head/]
[@b.grid items=stdAlterApplies var="stdAlterApply"]
  [@b.gridbar]
    bar.addItem("删除",action.remove());
  [/@]
  [@b.row]
    [@b.boxcol/]
    [@b.col property="std.code" title="学号"/]
    [@b.col property="std.name" title="姓名"][@b.a target="contentDiv" href="!info?id=${stdAlterApply.id}" target="_blank" title="查看该学生的学籍变动信息"]${(stdAlterApply.std.name)?if_exists}[/@][/@]
    [@b.col property="std.state.department.name" title="院系"]${(stdAlterApply.std.state.department.shortName)!stdAlterApply.std.state.department.name}[/@]
    [@b.col property="std.state.grade.name" title="年级"/]
    [@b.col property="std.state.major.name" title="专业"/]
    [@b.col property="alterType.name" title="异动类型"/]
    [@b.col property="status" title="状态" /]
    [@b.col property="alterFrom" title="生效日期"]${stdAlterApply.alterFrom}[/@]
  [/@]
[/@]
[@b.foot/]
