[#ftl]
[@b.head/]
[@b.toolbar title="新增辅修学生的主修信息"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action=b.rest.save(majorStudent) theme="list"]
    [@b.textfield name="userCode" label="辅修学号" value=""/]
    [@b.textfield name="majorStudent.code" label="主修学号" value=majorStudent.code!/]
    [@b.select name="majorStudent.school.id" label="主修学校" value=majorStudent.school!  style="width:200px;" items=schools empty="..." required="true"/]
    [@b.textfield name="majorStudent.majorName" label="主修专业" value=majorStudent.majorName! required="true" maxlength="100"/]
    [@b.textfield name="majorStudent.enMajorName" label="主修专业英文名" value=majorStudent.enMajorName! maxlength="100"/]
    [@b.select name="majorStudent.majorCategory.id" label="专业学科门类" value=majorStudent.majorCategory items=majorCategories empty="..." required="true"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
