[#if stds?size>0]
  [@b.grid items=stds?sort_by("code") var="student" theme="mini"]
    [@b.row]
      [@b.col title="序号" width="60px"]${student_index+1}[/@]
      [@b.col property="code" title="学号" width="120px"/]
      [@b.col property="name" title="姓名"]
        [@b.a href="/admin/search/${student.id}" target="_blank"]<div title="${student.name}" class="text-ellipsis">${student.name}</div>[/@]
      [/@]
      [@b.col property="gender.name" title="性别" width="50px"/]
      [@b.col property="level.name" title="培养层次" width="80px"/]
      [@b.col property="state.department.name" title="院系" width="90px"]
        ${student.state.department.shortName!student.state.department.name}
      [/@]
      [@b.col property="state.status.name" title="学籍状态"  width="110px"/]
      [@b.col property="stdType.name" title="学生类别" width="90px"/]
    [/@]
  [/@]
[#else]
  <p class="alert alert-warning">${beginOn}入学学生中，没有无需上报的学生</p>
[/#if]
