[#ftl]
[@b.head/]
  [@b.grid items=students var="student" sortable="true"]
  <div style="overflow-x:auto; width:400px">
    [@b.row]
      [@b.boxcol/]
      [@b.col property="user.code" title="学号" class="stdCode"/]
      [@b.col property="user.name" title="姓名" class="stdName"]
        [@b.a href="!info?id=${student.id}" target="_blank"]${(student.user.name)?if_exists}[/@]
      [/@]
      [@b.col property="person.gender.name" title="性别" class="stdGender"/]
      [@b.col property="state.department.name" title="院系" class="departName"/]
      [@b.col property="state.grade" title="年级" class="stdGrade"/]
      [@b.col property="state.major.name" title="专业" class="majorName"/]
      [@b.col property="duration" title="学制" class="duration"/]
      [@b.col property="state.squad.name" title="班级" class="duration"/]
      [@b.col property="state.status.name" title="学籍状态" class="stateStatus"/]
      [@b.col property="user.mobile" title="手机" class="mobile"/]
      [@b.col property="person.code" title="证件号码" class="PersonCode"/]
      [@b.col property="studyType.name" title="学习形式" class="studyType"/]
      [@b.col property="beginOn" title="入学年月" ]${(student.beginOn?string("yyyy-MM"))!}[/@]
    [/@]
    </div>
  [/@]
  <input type="hidden" id="totalNumber" value="${students.totalItems!}"/>
[@b.foot/]
