[#ftl]
[@b.head/]
[#macro getUpdateContent applyInfo]
  [#if (applyInfo.before.mail)?if_exists != (applyInfo.now.mail)?if_exists]
    [邮箱]变更前：${(applyInfo.before.mail)!}，变更后：${(applyInfo.now.mail)!}；<br/>
  [/#if]
  [#if (applyInfo.before.phone)! != (applyInfo.now.phone)!]
    [联系电话]变更前：${(applyInfo.before.phone)!}，变更后：${(applyInfo.now.phone)!}；<br/>
  [/#if]
  [#if (applyInfo.before.mobile)?if_exists != (applyInfo.now.mobile)?if_exists]
    [移动电话]变更前：${(applyInfo.before.mobile)!}，变更后：${(applyInfo.now.mobile)!}；<br/>
  [/#if]
  [#if (applyInfo.before.address)?if_exists != (applyInfo.now.address)?if_exists]
    [通讯地址]变更前：${(applyInfo.before.address)!}，变更后：${(applyInfo.now.address)!}；<br/>
  [/#if]
[/#macro]
  [@b.grid items=applyInfos var="applyInfo"]
      [#if auditType==0]
        [@b.gridbar]
        bar.addItem("通过修改", action.multi("saveEdit"));
        bar.addItem("打回", action.multi("backApplyEditInfo"))
        [/@]
      [/#if]
      [@b.row]
        [#if auditType==0]
          [@b.boxcol/]
        [/#if]
        [@b.col property="time" title="申请时间"]${(applyInfo.time?string("yyyy-MM-dd HH:mm"))?if_exists}[/@]
        [@b.col property="std.user.code" title="学号"]
          [@b.a href="!info?applyInfoId=${applyInfo.id}" target="_blank" title="查看修改内容"]${(applyInfo.std.user.code)?if_exists}[/@]
        [/@]
        [@b.col property="std.user.name" title="姓名"]
          [@b.a href="studentSearch!info?studentId=${(applyInfo.std.id)!}" target="_blank" title="查看"]${(applyInfo.std.user.name)?if_exists}[/@]
        [/@]
        [@b.col property="std.state.major.name" title="专业" /]
        [@b.col title="内容"][@getUpdateContent applyInfo/][/@]
        [#if auditType!=0][@b.col property="status" title="审核状态" ]${(auditType==1)?string("已通过","已打回")}[/@][/#if]
            [#if auditType!=0][@b.col property="auditTime" title="审核时间"]${(applyInfo.auditTime?string("yyyy-MM-dd HH:mm"))?if_exists}[/@][/#if]
        [/@]
     [/@]
[@b.foot/]
